name: CI - Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up build dependencies
      run: |
        bash -c '
        if [ "${{ runner.os }}" == "Linux" ]; then
          sudo apt update
          sudo apt install -y clang++
        elif [ "${{ runner.os }}" == "Windows" ]; then
          choco install -y mingw
        elif [ "${{ runner.os }}" == "Darwin" ]; then
          xcode-select --install || echo "xcode-select is already set up"
          brew install clang++ || echo "Homebrew dependencies are already set up"
          # Set the correct architecture for compatibility
          export CXXFLAGS="-arch x86_64 -arch arm64"
        fi
        '

    - name: Set environment flags for macOS
      if: runner.os == 'Darwin'
      run: |
        echo "Setting environment flags for macOS compatibility"
        export CXXFLAGS="-arch x86_64 -arch arm64"

    - name: Build the project
      run: make

    - name: Run tests
      run: make test

    - name: Cleanup
      run: make clean
