name: CI - Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up build dependencies
      run: |
        if [ "${{ runner.os }}" == "Linux" ]; then
          sudo apt update
          sudo apt install -y g++  # Install for Linux
        elif [ "${{ runner.os }}" == "Windows" ]; then
          choco install -y mingw
        elif [ "${{ runner.os }}" == "Darwin" ]; then
          brew install gcc
        fi

    - name: Build the project
      run: make

    - name: Run tests
      run: make test

    - name: Cleanup
      run: make clean
